import { z } from "zod";

/** Timestamps are seconds since source start, as plain numbers. Every layer
 * (plans, observations, reports) uses the same convention. */

const TimeRange = z.object({
  start: z.number().min(0),
  end: z.number().min(0),
});

/** trim = KEEP [start, end] on the source timeline. Multiple trims union. */
export const TrimOp = TimeRange.extend({ type: z.literal("trim") });

/** cut = REMOVE [start, end] from whatever the trims kept. */
export const CutOp = TimeRange.extend({ type: z.literal("cut") });

/** Single-pass EBU R128 loudness normalization (dynamic mode). */
export const NormalizeAudioOp = z.object({
  type: z.literal("normalize-audio"),
  /** Target integrated loudness in LUFS. Default -16 (online video norm). */
  target: z.number().min(-40).max(-5).optional(),
});

/** Global playback speed. Exactly one per plan; audio follows via atempo. */
export const SpeedOp = z.object({
  type: z.literal("speed"),
  factor: z.number().gt(0).max(10),
});

/** Global resize. Exactly one per plan; width-only keeps aspect ratio. */
export const ResizeOp = z.object({
  type: z.literal("resize"),
  width: z.number().int().gt(0).max(16384),
  height: z.number().int().gt(0).max(16384).optional(),
});

/** Global audio gain. Exactly one per plan; exactly one of db or factor. */
export const VolumeOp = z.object({
  type: z.literal("volume"),
  db: z.number().min(-60).max(40).optional(),
  factor: z.number().gt(0).max(10).optional(),
});

/** Burn an .srt into the output during the single render pass.
 * CRITICAL: cue times are interpreted against the EDITED OUTPUT timeline —
 * generate source-timed srt through `video captions --plan` to remap. */
export const CaptionsOp = z.object({
  type: z.literal("captions"),
  file: z.string().min(1),
  /** ASS force_style, e.g. "FontSize=24,PrimaryColour=&HFFFFFF&" */
  style: z.string().optional(),
});

/** Burn one text overlay (title card / lower third) during the single render
 * pass — ONE drawtext on the OUTPUT timeline (like captions). The text value
 * passes through TWO ffmpeg unescaping stages (filtergraph tokenizer, then
 * the option-value tokenizer), so it needs its own escaping helper
 * (escapeDrawText) — never reuse escapeFilterText for it. */
export const OverlayTextOp = z.object({
  type: z.literal("overlay-text"),
  /** literal text to burn; `%` is NOT special (expansion=none) */
  text: z.string().min(1).max(1024),
  /** visibility window on the OUTPUT timeline (s); both absent = always visible */
  from: z.number().min(0).optional(),
  to: z.number().min(0).optional(),
  /** vertical placement; default "bottom" */
  position: z.enum(["top", "center", "bottom"]).optional(),
  /** font size in output px; default 48 */
  fontsize: z.number().int().gt(0).max(512).optional(),
  /** ffmpeg color name or 0xRRGGBB[AA]; default "white". Filter-syntax
   * characters are rejected by the shape so the value can never need
   * escaping. */
  color: z
    .string()
    .max(64)
    .regex(
      /^(?:0x[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?|[A-Za-z][A-Za-z0-9_]*)$/,
      "must be 0xRRGGBB[AA] hex or an alphanumeric color name",
    )
    .optional(),
  /** semi-transparent backing box; default true */
  box: z.boolean().optional(),
});

/** Sidechain ducking parameters — map 1:1 to sidechaincompress filter keys
 * (validated graph: docs/ultron/research/r1-audio-mix-single-pass.md). */
export const AudioMixDuck = z.object({
  /** LINEAR amplitude 0.000976563–1 (≈ −60…0 dB) — NOT dB, unlike every
   * other dB-flavored key in the schema. Default 0.02 (≈ −34 dB). */
  threshold: z.number().min(0.000976563).max(1).optional(),
  /** compression ratio; 1 = no ducking. Default 8 (~18 dB measured depth). */
  ratio: z.number().min(1).max(20).optional(),
  /** ms before ducking engages. Default 20. */
  attack: z.number().min(0.01).max(2000).optional(),
  /** ms before ducking releases. Default 400. */
  release: z.number().min(0.01).max(9000).optional(),
  /** post-compression gain (1–64); omitted → ffmpeg default (1). */
  makeup: z.number().min(1).max(64).optional(),
});

/** Mix a music bed under the plan's audio with speech-keyed sidechain
 * ducking — in the SAME single ffmpeg pass (INVARIANT 1). The bed loops
 * (`-stream_loop -1`) and is trimmed to the timeline; it conforms to the
 * speech stream's own sample rate/layout (no extra probes). */
export const AudioMixOp = z.object({
  type: z.literal("audio-mix"),
  /** music bed; any ffmpeg-decodable audio file (must exist). */
  file: z.string().min(1),
  /** bed gain in dB (−60…0; default −18). */
  level: z.number().min(-60).max(0).optional(),
  duck: AudioMixDuck.optional(),
});

/** Crossfade transition kind — the FULL verified allowlist (T17): every kind
 * this build's `ffmpeg -h filter=xfade` enum lists, in the help's own order.
 * DERIVED FROM THE CATALOG, never hand-picked: generated by rendering each
 * catalog kind through the real transition chain on a tiny 2-segment fixture
 * (ffmpeg 9.0.1 ffmpeg-full, 2026-09-03 — all 58 passed: exit 0, duration law
 * timeline − (N−1)·fade frame-exact at 25 fps, decodable output, one
 * invocation each; evidence: production-log.md T17 WORKER entry). Still a
 * COMPILE-TIME `as const` tuple — the schema NEVER reads the live catalog at
 * parse time; equality with the catalog is enforced at TEST time in both
 * directions (committed fixture parse + live re-parse deepEqual this tuple).
 * The `custom` enum sentinel is EXCLUDED here (it needs `expr=`, not a
 * standalone transition); it parses via CROSSFADE_KIND_OR_CUSTOM solely so
 * validate can reject it with a specific fence. All kinds share the same
 * duration/offset semantics (R3: docs/ultron/research/r3-xfade-single-pass.md). */
export const CROSSFADE_KINDS = [
  "fade",
  "wipeleft",
  "wiperight",
  "wipeup",
  "wipedown",
  "slideleft",
  "slideright",
  "slideup",
  "slidedown",
  "circlecrop",
  "rectcrop",
  "distance",
  "fadeblack",
  "fadewhite",
  "radial",
  "smoothleft",
  "smoothright",
  "smoothup",
  "smoothdown",
  "circleopen",
  "circleclose",
  "vertopen",
  "vertclose",
  "horzopen",
  "horzclose",
  "dissolve",
  "pixelize",
  "diagtl",
  "diagtr",
  "diagbl",
  "diagbr",
  "hlslice",
  "hrslice",
  "vuslice",
  "vdslice",
  "hblur",
  "fadegrays",
  "wipetl",
  "wipetr",
  "wipebl",
  "wipebr",
  "squeezeh",
  "squeezev",
  "zoomin",
  "fadefast",
  "fadeslow",
  "hlwind",
  "hrwind",
  "vuwind",
  "vdwind",
  "coverleft",
  "coverright",
  "coverup",
  "coverdown",
  "revealleft",
  "revealright",
  "revealup",
  "revealdown",
] as const;

/** The enum the schema parses = the verified allowlist + the `custom`
 * sentinel, which parses ONLY to be routed to validate's fence (an
 * OPERATION_INVALID naming `expr=`) instead of a generic enum rejection.
 * `custom` is deliberately NOT in CROSSFADE_KINDS: it is not a standalone
 * transition and never appears in the live catalog (enum value −1). */
const CROSSFADE_KIND_OR_CUSTOM = [...CROSSFADE_KINDS, "custom"] as const;

/** Join consecutive keep-segments with crossfade transitions (video `xfade` +
 * audio `acrossfade`), still in ONE ffmpeg pass (INVARIANT 1 — R3's validated
 * chain). TIMELINE-affecting: output duration = timeline − (N−1)·duration.
 * Client-side bounds are load-bearing — ffmpeg silently corrupts when the
 * fade reaches a segment length or drops below one frame. */
export const CrossfadeOp = z.object({
  type: z.literal("crossfade"),
  /** fade duration per join, seconds (> 0; validate enforces the real
   * floor: ≥ 0.05 s and ≥ one source frame, and < EVERY keep-segment) */
  duration: z.number().gt(0).max(60),
  /** xfade transition name; default "fade". `custom` parses but is rejected
   * by validate (the xfade `expr=` sentinel — not a standalone transition) */
  kind: z.enum(CROSSFADE_KIND_OR_CUSTOM).default("fade"),
});

/** Ken Burns camera motion over the whole program (plan op `zoom`; R5's
 * committed contract, docs/ultron/research/r5-zoom-motion.md). VISUAL-ONLY:
 * zoom never enters any duration law. `mode` is CAMERA direction — pan
 * `right` = the view moves right = the content drifts left. */
export const ZoomOp = z.object({
  type: z.literal("zoom"),
  /** camera motion; default "in" (center-anchored zoom) */
  mode: z.enum(["in", "out", "left", "right", "up", "down"]).default("in"),
  /** zoom level; default 1.2 (applied by the render layer — the schema keeps
   * the value raw so validate can emit its own OPERATION_INVALID fence for
   * 1.0 < f ≤ 2.0 rather than a generic Zod rejection) */
  factor: z.number().optional(),
  /** ramp easing; default "smooth" (smoothstep 3p²−2p³, classic Ken Burns) */
  easing: z.enum(["smooth", "linear"]).default("smooth"),
});

/** Export op — TERMINAL (must be the LAST operation; validate enforces the
 * position): changes the output FORMAT, not the content, so it is NOT a
 * TransformOpType member. First of an export-op class. Renders the compiled
 * OUTPUT timeline (post trim/cut, crossfade-adjusted, post-speed) to an
 * animated GIF in the SAME single ffmpeg invocation — the palette is
 * generated inside the one `-filter_complex` via `split` (recipe proven in
 * vedit's build_gif, vedit.py:363-375; the classic two-pass palette workflow
 * would violate INVARIANT 1 and is never used). GIF carries no audio: the
 * audio stream is dropped by design (validate warns GIF_AUDIO_DROPPED). */
export const ExportGifOp = z.object({
  type: z.literal("export-gif"),
  /** output width in px (int, mirror resize); height keeps aspect (-2, even).
   * Default 480 (vedit's proven value). */
  width: z.number().int().gt(0).max(16384).optional(),
  /** output fps. Default 12 (vedit's proven value). */
  fps: z.number().gt(0).max(60).optional(),
  /** sub-range of the OUTPUT timeline (s); both absent = the whole output */
  from: z.number().min(0).optional(),
  to: z.number().min(0).optional(),
});

/** Transform ops apply to the whole output; they never affect which source
 * ranges are kept (that stays the trim/cut pair). At most one of each. */
export type TransformOpType =
  | "speed"
  | "resize"
  | "volume"
  | "captions"
  | "overlay-text"
  | "audio-mix"
  | "zoom";

export const Operation = z.discriminatedUnion("type", [
  TrimOp,
  CutOp,
  NormalizeAudioOp,
  SpeedOp,
  ResizeOp,
  VolumeOp,
  CaptionsOp,
  OverlayTextOp,
  AudioMixOp,
  CrossfadeOp,
  ExportGifOp,
  ZoomOp,
]);

export const OutputSpec = z.object({
  path: z.string().min(1),
  mode: z.enum(["final", "preview"]).default("final"),
});

export const EditPlan = z.object({
  version: z.literal(1),
  source: z.string().min(1),
  operations: z.array(Operation).default([]),
  output: OutputSpec,
});

export type Operation = z.infer<typeof Operation>;
export type EditPlan = z.infer<typeof EditPlan>;
export type OutputSpec = z.infer<typeof OutputSpec>;

// ---- observation schemas (analysis workers emit these; render never reads them)

export const SilenceSegment = z.object({
  start: z.number(),
  end: z.number(),
  duration: z.number(),
});

export const SilenceReport = z.object({
  segments: z.array(SilenceSegment),
  duration: z.number().optional(),
  note: z.string().optional(),
  params: z.object({ thresholdDb: z.number(), minDurationSec: z.number() }).optional(),
});

export const SceneBoundary = z.object({
  timestamp: z.number(),
  confidence: z.number().min(0).max(1),
});
export const SceneReport = z.object({
  boundaries: z.array(SceneBoundary),
  duration: z.number().optional(),
  note: z.string().optional(),
  params: z.object({ threshold: z.number() }).optional(),
});

export const WordTiming = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
});
export const TranscriptSegment = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
  /** per-word timings (seconds, 3 decimals); present only when the engine
   * produced them (whisper-cpp `--word-timestamps`) — consumers must treat
   * absence as "segment granularity only" */
  words: z.array(WordTiming).optional(),
});
export const TranscriptReport = z.object({
  segments: z.array(TranscriptSegment),
  duration: z.number().optional(),
  engine: z.string().optional(),
  model: z.string().optional(),
  language: z.string().optional(),
  note: z.string().optional(),
  params: z
    .object({
      chunkSeconds: z.number().optional(),
      snapToSilence: z.boolean().optional(),
      model: z.string().optional(),
      /** native-segment engines (no windowing) record the words flag here */
      wordTimestamps: z.boolean().optional(),
    })
    .optional(),
});

export const FillerInstance = z.object({
  start: z.number(),
  end: z.number(),
  phrase: z.string(),
  context: z.string(),
});
export const FillerReport = z.object({
  instances: z.array(FillerInstance),
  duration: z.number().optional(),
  note: z.string().optional(),
  params: z
    .object({
      phrases: z.array(z.string()),
      /** which timing source produced the instance times: exact per-word
       * anchors ("words", from segments[].words) vs linear interpolation
       * within each segment ("segments"). Optional so pre-T11 filler
       * reports (params without precision) still parse. */
      precision: z.enum(["words", "segments"]).optional(),
    })
    .optional(),
});

export const HighlightCandidate = z.object({
  start: z.number(),
  end: z.number(),
  score: z.number().min(0).max(1),
  text: z.string(),
  reasons: z.array(z.string()),
});
export const HighlightReport = z.object({
  candidates: z.array(HighlightCandidate),
  duration: z.number().optional(),
  note: z.string().optional(),
  params: z
    .object({
      keywords: z.array(z.string()),
      minScore: z.number(),
      maxCount: z.number(),
    })
    .optional(),
});

/** Loudness first-pass measurement (loudnorm analysis pass; the
 * `measure-loudness` worker). Values are exactly as loudnorm emits them —
 * LUFS for inputI/inputThresh, dBTP for inputTP, LU for inputLRA — NOT
 * rounded (only timestamps round). All four measurement fields are ABSENT
 * when there is nothing to measure: an audio-less source returns only
 * `{duration, note}` (the established empty-report pattern), and audio that
 * loudnorm measures as digital silence (`-inf`) returns the same empty
 * shape with its own note. */
export const LoudnessReport = z.object({
  /** integrated loudness (LUFS) */
  inputI: z.number().optional(),
  /** true peak (dBTP) */
  inputTP: z.number().optional(),
  /** loudness range (LU) */
  inputLRA: z.number().optional(),
  /** integrated-loudness threshold (LUFS, ≈ inputI − 10) */
  inputThresh: z.number().optional(),
  duration: z.number().optional(),
  note: z.string().optional(),
  params: z
    .object({
      /** the loudnorm target I used by the measurement invocation (LUFS) */
      targetI: z.number(),
    })
    .optional(),
});

/** Compact a ZodError into machine-readable issues with stable paths. */
export function schemaIssues(error: z.ZodError): {
  path: string;
  message: string;
  code: string;
}[] {
  return error.issues.map((issue) => ({
    path: issue.path.map(String).join(".") || "(root)",
    message: issue.message,
    code: issue.code,
  }));
}
